/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RaboForm {
    }
    interface RaboInput {
    }
}
declare global {
    interface HTMLRaboFormElement extends Components.RaboForm, HTMLStencilElement {
    }
    var HTMLRaboFormElement: {
        prototype: HTMLRaboFormElement;
        new (): HTMLRaboFormElement;
    };
    interface HTMLRaboInputElement extends Components.RaboInput, HTMLStencilElement {
    }
    var HTMLRaboInputElement: {
        prototype: HTMLRaboInputElement;
        new (): HTMLRaboInputElement;
    };
    interface HTMLElementTagNameMap {
        "rabo-form": HTMLRaboFormElement;
        "rabo-input": HTMLRaboInputElement;
    }
}
declare namespace LocalJSX {
    interface RaboForm {
    }
    interface RaboInput {
    }
    interface IntrinsicElements {
        "rabo-form": RaboForm;
        "rabo-input": RaboInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rabo-form": LocalJSX.RaboForm & JSXBase.HTMLAttributes<HTMLRaboFormElement>;
            "rabo-input": LocalJSX.RaboInput & JSXBase.HTMLAttributes<HTMLRaboInputElement>;
        }
    }
}
